// Real OWL templates, mocked RPC. All fixture amounts are synthetic.
// node check_executive_frontend.cjs /tmp/hmx-qa
const fs = require('fs'), path = require('path'), assert = require('node:assert/strict');
const qa = process.argv[2];
const {JSDOM} = require(path.join(qa, 'node_modules/jsdom'));
const root = path.resolve(__dirname, '..');
const w = new JSDOM('<html><body><main id="mount"></main></body></html>', {runScripts:'outside-only',pretendToBeVisual:true,url:'http://localhost/'}).window;
w.eval(fs.readFileSync(path.join(qa,'node_modules/@odoo/owl/dist/owl.iife.js'),'utf8'));
const fixtures = JSON.parse(fs.readFileSync(path.join(qa,'fixtures.json'),'utf8'));
const templates = ['analytics.xml','executive.xml'].map(file => fs.readFileSync(path.join(root,'static/src',file),'utf8').replace(/<\?xml[^>]*>/,'').replace(/<templates[^>]*>/,'').replace('</templates>','')).join('');
const calls=[], actions=[], deferred=[];
let mode='normal';
w.services = {orm:{call:async(model,method,args) => {
 calls.push({method,args});
 if(method === 'get_options') return structuredClone(fixtures.options);
 if(method === 'get_filter_options') return fixtures.options[args[0]+'s'];
 if(mode === 'deferred') return new Promise(resolve=>deferred.push({args,resolve}));
 if(mode === 'denied') {const e=new Error('Revocado');e.data={name:'odoo.exceptions.AccessError'};throw e;}
 if(mode === 'dof' && args[1]?.currency_id === 0 && fixtures.consolidated[args[0]]) return structuredClone(fixtures.consolidated[args[0]]);
 if(mode === 'dofError' && args[1]?.currency_id === 0) return {...structuredClone(fixtures.mixed[args[0]]),fx:{applied:false,error:'No hay promedio DOF verificable para 2026-09.',rates:[]}};
 return structuredClone(args[1]?.currency_id === 0 && fixtures.mixed[args[0]] ? fixtures.mixed[args[0]] : fixtures.dashboards[args[0]]);
}}, action:{doAction:async a=>actions.push(a)}, dialog:{add:()=>{}}, notification:{add:()=>{}}};
w.Chart=class {static version='4.4.1';constructor(canvas, config){this.config=config;}destroy(){}};
w.eval(`const {Component,onWillStart,onWillUnmount,useState,useEffect,useRef,useExternalListener}=owl;
const useService=name=>services[name]; const user={userId:12}; const loadBundle=async()=>{};
const registry={category:()=>({add:(k,v)=>window.Dashboard=v})};
class Dialog extends Component {static props=['*'];static template=owl.xml\`<div><t t-slot="default"/></div>\`;}
`+['mixed.js','charts.js','analytics.js'].map(f=>fs.readFileSync(path.join(root,'static/src',f),'utf8').replace(/^import .*;\n/gm,'').replace(/export (class|function) /g,'$1 ')).join('\n'));
const tick=()=>new Promise(r=>setTimeout(r,50));
(async()=>{
 const app=new w.owl.App(w.Dashboard,{templates:`<templates>${templates}</templates>`});
 const component=await app.mount(w.document.querySelector('#mount'));
 assert.equal(w.document.querySelectorAll('.hmx_exec_metrics article').length,3);
 assert.equal(w.document.querySelectorAll('header').length,1);
 assert.ok(!w.document.querySelector('select[name=company_id]'));
 assert.equal(w.document.querySelectorAll('canvas').length,8);
 assert.equal(w.document.querySelector('select[name=currency_id]').value,'1');
 console.log('PASS real OWL compiles and mounts executive templates, 8 charts, one header');
 w.document.querySelector('.hmx_value').click();await tick();
 assert.equal(actions[0].res_model,'sale.order.line');
 assert.ok(actions[0].domain.some(t=>t[0]==='company_id'&&t[2]===1));
 console.log('PASS monetary card opens its exact server domain');
 for(const tab of fixtures.options.tabs){await component.load(tab.key);await tick();assert.ok(!w.document.body.textContent.includes('NaN'));}
 console.log('PASS all executive and operational views render without NaN or template errors');
 const currency=w.document.querySelector('select[name=currency_id]');
 assert.ok(currency && !currency.closest('.hmx_more'));
 component.changeCurrency({target:{value:'0'}});await tick();await tick();
 await component.load('resumen');await tick();
 assert.equal(w.document.querySelectorAll('.hmx_currency_block').length,0);
 assert.equal(w.document.querySelectorAll('.hmx_heatmap').length,1);
 assert.equal(w.document.querySelector('select[name=currency_id]').value,'0');
 assert.equal(w.document.querySelectorAll('.hmx_exec_metrics article').length,3);
 assert.ok(w.document.body.textContent.includes('800 USD'));
 assert.ok(w.document.body.textContent.includes('350 MXN'));
 assert.equal(component.state.data.customers.rows.length,3);
 assert.equal(component.state.data.customers.cohorts.find(row=>row.key==='recurring').count,2);
 const shared=component.state.data.customers.rows.find(row=>row.id===1);
 assert.equal(shared.currency_values.length,2);
 const usdCard=Array.from(w.document.querySelectorAll('.hmx_exec_metrics .hmx_value')).find(el=>el.textContent==='800 USD');
 usdCard.click();await tick();
 assert.ok(actions.at(-1).domain.some(t=>t[0]==='currency_id'&&t[2]===2));
 for(const tab of ['comercial','clientes','productos']){
  await component.load(tab);await tick();
  assert.equal(w.document.querySelectorAll('.hmx_exec_metrics article').length,3);
  assert.ok(!w.document.body.textContent.includes('NaN'));
  assert.equal(w.document.querySelectorAll('.hmx_method').length,1);
  const keys=component.charts.map(chart=>chart.key);
  assert.equal(new Set(keys).size,keys.length);
  assert.ok(component.charts.every(chart=>chart.facets.length===2));
 }
 console.log('PASS unified mixed cards/charts/customers in all commercial views; unique customer counts; USD detail keeps its currency');
 mode='dof';await component.load('resumen');await tick();
 assert.ok(w.document.querySelector('.hmx_fx').textContent.includes('20.000000'));
 assert.equal(w.document.querySelectorAll('.hmx_exec_metrics article').length,3);
 assert.equal(w.document.querySelectorAll('.hmx_value')[0].textContent,'16,350 MXN');
 assert.equal(w.document.querySelectorAll('.hmx_mixed_chart').length,0);
 assert.equal(w.document.querySelectorAll('canvas').length,8);
 assert.equal(w.document.querySelectorAll('.hmx_heatmap').length,1);
 w.document.querySelector('.hmx_value').click();await tick();
 assert.ok(actions.at(-1).domain.some(t=>t[0]==='currency_id'&&t[1]==='in'&&t[2].includes(1)&&t[2].includes(2)));
 for(const tab of ['comercial','clientes','productos']){
  await component.load(tab);await tick();assert.ok(w.document.body.textContent.includes('MXN consolidado'));
  assert.ok(!w.document.body.textContent.includes('NaN'));
 }
 mode='dofError';await component.load('resumen');await tick();
 assert.ok(w.document.querySelector('.hmx_fx').textContent.includes('No se pudo consolidar'));
 assert.ok(w.document.body.textContent.includes('800 USD'));
 mode='normal';
 console.log('PASS DOF consolidated cards/charts and original-document drill; monthly audit and explicit fallback on missing rate');
 component.changeCurrency({target:{value:'1'}});await tick();await tick();
 await component.load('clientes');await tick();
 assert.ok(w.document.body.textContent.includes('Reactivado'));
 assert.equal(w.document.querySelectorAll('.hmx_heatmap tbody tr').length,3);
 component.changeCustomerList('customerStatus','reactivated');await tick();
 assert.equal(component.customerRows.length,1);
 console.log('PASS heatmap and cohort filtering');
 component.toggleWarehouse(2,true);await tick();
 assert.equal(component.state.data,null);
 assert.ok(w.document.body.textContent.includes('Aplicar cambios para consultar'));
 assert.ok(w.document.querySelector('.hmx_primary').textContent.includes('Aplicar cambios'));
 assert.equal(component.activeFilters.length,1);
 await component.load('produccion');await tick();
 assert.deepEqual(Array.from(calls.at(-1).args[1].warehouse_ids),[2]);
 assert.ok(w.document.body.textContent.includes('Almacén 2'));
 console.log('PASS filters persist across views and stale values disappear before apply');
 component.removeFilter(component.activeFilters[0]);await tick();await tick();
 assert.equal(component.state.filters.warehouse_ids.length,0);
 assert.equal(w.document.querySelectorAll('.hmx_filter_chip').length,0);
 assert.equal(component.primaryTabs.length,5);
 assert.equal(component.navigationGroups.flatMap(group=>group.tabs).length,6);
 assert.equal(component.selectedPreset,'mes');
 console.log('PASS compact header, primary/grouped navigation and individual filter removal');
 mode='deferred';const old=component.load('clientes');const latest=component.load('productos');
 deferred[1].resolve(fixtures.dashboards.productos);await latest;await tick();
 deferred[0].resolve(fixtures.dashboards.clientes);await old;await tick();
 assert.equal(component.state.tab,'productos');
 console.log('PASS late RPC cannot overwrite the active view');
 mode='denied';await component.load();await tick();assert.equal(w.document.querySelectorAll('.hmx_analytics').length,0);
 console.log('PASS access revocation removes dashboard');
 app.destroy();w.close();
})().catch(e=>{console.error(e);w.close();process.exitCode=1});
